### ISSUE TITLE
ability to upload images from sub folders

### ISSUE THREAD

**Issue by myannou** [vaakash/git-it-write#27]
Images have to present only in `_images` folder in the repository root.
It would be very convenient to accept images from subfolders containing an `_images` folder so that images in the git repo containing several dirs are not mixed with others (useful in the blog post usecase for instance)

**Comment by vaakash** [comment]
This is addressed in v1.7. Marking this as closed.

**Comment by myannou** [comment]
Hello,
It works correctly with 
```
/_images/image_0.jpg
/_images/subdir_1/image_1.jpg
/_images/subdir_2/image_2.jpg
``` 

but it doesn't work in this situation
```
/subdir_1/_images/image_1.jpg
/subdir_2/_images/image_2.jpg
``` 
It would be very convenient to accept images from subfolders (of the root) containing an _images sub folder 
(this is for the usecase where you have a blog per directory and I would like to have images inside the directory of the blog and not in the root _images dir.

Do you think it is possible to have this behaviour ?
Thanks

**Comment by vaakash** [comment]
Hi @myannou,

I understand the requirement. But the assumption is that all images must be under one folder so that the plugin can stick to that. It becomes to difficult to diffierentiate between folders which has posts and images. Rewriting this logic will make things complicated for a limited usecase.

We can sure come back to this, when more people are interested of the same.

Thanks,
Aakash
